/**
 * generate_seed.js
 * Convierte backup_final_sesion.sql (UTF-16) a seed_data.sql (INSERTs compatibles con Render)
 * Ejecutar: node generate_seed.js
 */
const fs = require('fs');
const path = require('path');

const backupFile = path.join(__dirname, 'backup_final_sesion.sql');
const outputFile = path.join(__dirname, 'db', 'seed_data.sql');

const b = fs.readFileSync(backupFile);
const content = b.toString('utf16le');
const lines = content.split(/\r?\n/);

let section = null;
let columns = [];
const sqlLines = ['-- Auto-generated seed data from backup_final_sesion.sql\n-- Generated by generate_seed.js\n\n'];

// Sequence reset values
const maxIds = { doctors: 0, products: 0, inventory_stocks: 0, sales_history: 0 };

function escapeValue(val, col) {
  if (val === '\\N' || val === null || val === undefined) return 'NULL';
  // Timestamps and dates: keep as-is, wrap in quotes
  if (col && (col.includes('_at') || col === 'sale_date')) return `'${val.replace(/'/g, "''")}'`;
  // Numeric columns
  if (!isNaN(val) && val.trim() !== '') return val.trim();
  // Strings
  return `'${val.replace(/'/g, "''")}'`;
}

for (const rawLine of lines) {
  const line = rawLine.replace(/\r$/, '');

  const copyMatch = line.match(/^COPY public\.(doctors|products|inventory_stocks|sales_history) \(([^)]+)\) FROM stdin;/);
  if (copyMatch) {
    section = copyMatch[1];
    columns = copyMatch[2].split(', ').map(c => c.trim());
    sqlLines.push(`-- Table: ${section}\n`);
    continue;
  }

  if (line === '\\.' || line === '\\.') {
    section = null;
    sqlLines.push('\n');
    continue;
  }

  if (section && line.trim()) {
    const values = line.split('\t');
    
    // Track max ID for sequence reset
    const idIdx = columns.indexOf('id');
    if (idIdx >= 0 && values[idIdx] && !isNaN(values[idIdx])) {
      maxIds[section] = Math.max(maxIds[section], parseInt(values[idIdx]));
    }

    const escaped = values.map((v, i) => escapeValue(v, columns[i]));
    const colList = columns.map(c => `"${c}"`).join(', ');
    sqlLines.push(`INSERT INTO ${section} (${colList}) VALUES (${escaped.join(', ')}) ON CONFLICT (id) DO NOTHING;\n`);
  }
}

// Add sequence resets at the end
sqlLines.push('\n-- Reset sequences to avoid ID conflicts\n');
for (const [table, maxId] of Object.entries(maxIds)) {
  if (maxId > 0) {
    sqlLines.push(`SELECT setval('${table}_id_seq', ${maxId + 1}, false);\n`);
  }
}

fs.writeFileSync(outputFile, sqlLines.join(''), 'utf8');
console.log(`✅ Seed file generated: ${outputFile}`);
console.log(`   Max IDs:`, maxIds);
